"""Register the complete schema on one Base before migrations or mapper use.

Files owns storage identities and claim triggers; Finance owns ledger and cutover records.
The remaining records keep their existing relationships together.
"""

from core.schema.application import Album as Album
from core.schema.application import AndromedaSavedSearch as AndromedaSavedSearch
from core.schema.application import AndromedaVerificationJob as AndromedaVerificationJob
from core.schema.application import ApiToken as ApiToken
from core.schema.application import Attachment as Attachment
from core.schema.application import AuditRecord as AuditRecord
from core.schema.application import AutomationAttempt as AutomationAttempt
from core.schema.application import AutomationRule as AutomationRule
from core.schema.application import Blob as Blob
from core.schema.application import Book as Book
from core.schema.application import BookingPage as BookingPage
from core.schema.application import BrowserConnection as BrowserConnection
from core.schema.application import CachedMessage as CachedMessage
from core.schema.application import Calendar as Calendar
from core.schema.application import CalendarEvent as CalendarEvent
from core.schema.application import CalendarSubscription as CalendarSubscription
from core.schema.application import CapabilityGrant as CapabilityGrant
from core.schema.application import CapabilityGrantEvent as CapabilityGrantEvent
from core.schema.application import CommitmentCreateReceipt as CommitmentCreateReceipt
from core.schema.application import Connection as Connection
from core.schema.application import Contact as Contact
from core.schema.application import ContactField as ContactField
from core.schema.application import ContactGroup as ContactGroup
from core.schema.application import ContactGroupMember as ContactGroupMember
from core.schema.application import ContactLink as ContactLink
from core.schema.application import CookbookEntry as CookbookEntry
from core.schema.application import DayEvent as DayEvent
from core.schema.application import DelegatedAction as DelegatedAction
from core.schema.application import EventAttendee as EventAttendee
from core.schema.application import Face as Face
from core.schema.application import GalleryImage as GalleryImage
from core.schema.application import Habit as Habit
from core.schema.application import HabitCreateReceipt as HabitCreateReceipt
from core.schema.application import HabitLog as HabitLog
from core.schema.application import HealthCreateReceipt as HealthCreateReceipt
from core.schema.application import HealthEntry as HealthEntry
from core.schema.application import HealthImportReceipt as HealthImportReceipt
from core.schema.application import Insight as Insight
from core.schema.application import JarvisConnector as JarvisConnector
from core.schema.application import JarvisDeliveryAttempt as JarvisDeliveryAttempt
from core.schema.application import JarvisInboxEvent as JarvisInboxEvent
from core.schema.application import JarvisRun as JarvisRun
from core.schema.application import JarvisRunEvent as JarvisRunEvent
from core.schema.application import JarvisRunPrompt as JarvisRunPrompt
from core.schema.application import JarvisTrigger as JarvisTrigger
from core.schema.application import JarvisWorkflow as JarvisWorkflow
from core.schema.application import JournalEntry as JournalEntry
from core.schema.application import MailAccount as MailAccount
from core.schema.application import MailAccountDeletion as MailAccountDeletion
from core.schema.application import MailDraft as MailDraft
from core.schema.application import MailRule as MailRule
from core.schema.application import McpServer as McpServer
from core.schema.application import Memory as Memory
from core.schema.application import Message as Message
from core.schema.application import ModelEndpoint as ModelEndpoint
from core.schema.application import ModelVote as ModelVote
from core.schema.application import Monitor as Monitor
from core.schema.application import MonitorCheck as MonitorCheck
from core.schema.application import MutationEvent as MutationEvent
from core.schema.application import NewsBrief as NewsBrief
from core.schema.application import NewsConfiguration as NewsConfiguration
from core.schema.application import NewsEntry as NewsEntry
from core.schema.application import NewsSource as NewsSource
from core.schema.application import Person as Person
from core.schema.application import Persona as Persona
from core.schema.application import PersonaDoc as PersonaDoc
from core.schema.application import Photo as Photo
from core.schema.application import ProactiveItem as ProactiveItem
from core.schema.application import ProactiveOutcome as ProactiveOutcome
from core.schema.application import ProactiveState as ProactiveState
from core.schema.application import Project as Project
from core.schema.application import PushSubscription as PushSubscription
from core.schema.application import ReadFeed as ReadFeed
from core.schema.application import ReadItem as ReadItem
from core.schema.application import Reminder as Reminder
from core.schema.application import ReminderCreateReceipt as ReminderCreateReceipt
from core.schema.application import ResearchFinding as ResearchFinding
from core.schema.application import SavedSearch as SavedSearch
from core.schema.application import ScheduledMail as ScheduledMail
from core.schema.application import Session as Session
from core.schema.application import SignalSnapshot as SignalSnapshot
from core.schema.application import Task as Task
from core.schema.application import ToolChain as ToolChain
from core.schema.application import Upload as Upload
from core.schema.application import Vault as Vault
from core.schema.application import VaultAttachment as VaultAttachment
from core.schema.application import VaultCreateReceipt as VaultCreateReceipt
from core.schema.application import VaultEntry as VaultEntry
from core.schema.application import VaultShare as VaultShare
from core.schema.application import VaultUploadReceipt as VaultUploadReceipt
from core.schema.application import WebAuthnCredential as WebAuthnCredential
from core.schema.application import Webhook as Webhook
from core.schema.base import Base as Base
from core.schema.base import EncryptedText as EncryptedText
from core.schema.files import DEFAULT_LOCAL_STORAGE_LOCATION_ID as DEFAULT_LOCAL_STORAGE_LOCATION_ID
from core.schema.files import DocComment as DocComment
from core.schema.files import DocRevision as DocRevision
from core.schema.files import FileComment as FileComment
from core.schema.files import FileOperation as FileOperation
from core.schema.files import FileOperationPathClaim as FileOperationPathClaim
from core.schema.files import FileOperationSourceClaim as FileOperationSourceClaim
from core.schema.files import FileTag as FileTag
from core.schema.files import FileVersion as FileVersion
from core.schema.files import IndexChunk as IndexChunk
from core.schema.files import OfflineFile as OfflineFile
from core.schema.files import Share as Share
from core.schema.files import StorageLocation as StorageLocation
from core.schema.files import TrashItem as TrashItem
from core.schema.files import (
    canonical_local_physical_claim_path as canonical_local_physical_claim_path,
)
from core.schema.files import local_claim_case_insensitive as local_claim_case_insensitive
from core.schema.files import normalize_file_identity_path as normalize_file_identity_path
from core.schema.finance import Account as Account
from core.schema.finance import ActualEntityLink as ActualEntityLink
from core.schema.finance import ActualMigrationRun as ActualMigrationRun
from core.schema.finance import Budget as Budget
from core.schema.finance import BudgetAssignment as BudgetAssignment
from core.schema.finance import CategoryRule as CategoryRule
from core.schema.finance import FinanceConnection as FinanceConnection
from core.schema.finance import FinanceCreateReceipt as FinanceCreateReceipt
from core.schema.finance import FinanceImportBatch as FinanceImportBatch
from core.schema.finance import FinanceImportRow as FinanceImportRow
from core.schema.finance import FinanceLedgerState as FinanceLedgerState
from core.schema.finance import FundingTarget as FundingTarget
from core.schema.finance import Goal as Goal
from core.schema.finance import Holding as Holding
from core.schema.finance import MoneyFxEvidence as MoneyFxEvidence
from core.schema.finance import PriceHistory as PriceHistory
from core.schema.finance import RecurringTxn as RecurringTxn
from core.schema.finance import SubPayment as SubPayment
from core.schema.finance import SubPriceChange as SubPriceChange
from core.schema.finance import Subscription as Subscription
from core.schema.finance import TagRule as TagRule
from core.schema.finance import Transaction as Transaction
from core.schema.finance import TxnSplit as TxnSplit
from core.schema.finance import Watch as Watch
